/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PomHeaderIconItem {
    'icon': string;
    'url': string;
  }
  interface PomHeaderIconItemAttributes extends StencilHTMLAttributes {
    'icon'?: string;
    'url'?: string;
  }

  interface PomHeaderItem {
    'description': string;
    'url': string;
  }
  interface PomHeaderItemAttributes extends StencilHTMLAttributes {
    'description'?: string;
    'url'?: string;
  }

  interface PomHeader {
    'mainTitle': string;
    'showPercentage': boolean;
    'subTitle': string;
  }
  interface PomHeaderAttributes extends StencilHTMLAttributes {
    'mainTitle'?: string;
    'showPercentage'?: boolean;
    'subTitle'?: string;
  }

  interface PomShareButton {
    'social': 'facebook' | 'twitter' | 'linkedin' | 'email';
    'tutorialName': string;
  }
  interface PomShareButtonAttributes extends StencilHTMLAttributes {
    'social'?: 'facebook' | 'twitter' | 'linkedin' | 'email';
    'tutorialName'?: string;
  }

  interface PomShareButtons {
    'tutorialName': string;
  }
  interface PomShareButtonsAttributes extends StencilHTMLAttributes {
    'tutorialName'?: string;
  }

  interface PomTagsListItem {
    'mainTitle': string;
    'slug': string;
  }
  interface PomTagsListItemAttributes extends StencilHTMLAttributes {
    'mainTitle'?: string;
    'slug'?: string;
  }

  interface PomTagsList {
    'slug': string;
    'title': string;
  }
  interface PomTagsListAttributes extends StencilHTMLAttributes {
    'slug'?: string;
    'title'?: string;
  }

  interface PomTutorialCodeSnippet {
    'code': string;
    'language': string;
  }
  interface PomTutorialCodeSnippetAttributes extends StencilHTMLAttributes {
    'code'?: string;
    'language'?: string;
  }

  interface PomTutorialImage {
    'alt': string;
    'caption': string;
    'src': string;
  }
  interface PomTutorialImageAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'caption'?: string;
    'src'?: string;
  }

  interface PomTutorial {
    'content': string;
    'createdAt': string;
    'duration': number;
    'mainTitle': string;
  }
  interface PomTutorialAttributes extends StencilHTMLAttributes {
    'content'?: string;
    'createdAt'?: string;
    'duration'?: number;
    'mainTitle'?: string;
  }

  interface PomTutorialsListItem {
    'createdAt': Date;
    'mainTitle': string;
    'shortDescription': string;
  }
  interface PomTutorialsListItemAttributes extends StencilHTMLAttributes {
    'createdAt'?: Date;
    'mainTitle'?: string;
    'shortDescription'?: string;
  }

  interface PomTutorialsList {}
  interface PomTutorialsListAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'PomHeaderIconItem': Components.PomHeaderIconItem;
    'PomHeaderItem': Components.PomHeaderItem;
    'PomHeader': Components.PomHeader;
    'PomShareButton': Components.PomShareButton;
    'PomShareButtons': Components.PomShareButtons;
    'PomTagsListItem': Components.PomTagsListItem;
    'PomTagsList': Components.PomTagsList;
    'PomTutorialCodeSnippet': Components.PomTutorialCodeSnippet;
    'PomTutorialImage': Components.PomTutorialImage;
    'PomTutorial': Components.PomTutorial;
    'PomTutorialsListItem': Components.PomTutorialsListItem;
    'PomTutorialsList': Components.PomTutorialsList;
  }

  interface StencilIntrinsicElements {
    'pom-header-icon-item': Components.PomHeaderIconItemAttributes;
    'pom-header-item': Components.PomHeaderItemAttributes;
    'pom-header': Components.PomHeaderAttributes;
    'pom-share-button': Components.PomShareButtonAttributes;
    'pom-share-buttons': Components.PomShareButtonsAttributes;
    'pom-tags-list-item': Components.PomTagsListItemAttributes;
    'pom-tags-list': Components.PomTagsListAttributes;
    'pom-tutorial-code-snippet': Components.PomTutorialCodeSnippetAttributes;
    'pom-tutorial-image': Components.PomTutorialImageAttributes;
    'pom-tutorial': Components.PomTutorialAttributes;
    'pom-tutorials-list-item': Components.PomTutorialsListItemAttributes;
    'pom-tutorials-list': Components.PomTutorialsListAttributes;
  }


  interface HTMLPomHeaderIconItemElement extends Components.PomHeaderIconItem, HTMLStencilElement {}
  var HTMLPomHeaderIconItemElement: {
    prototype: HTMLPomHeaderIconItemElement;
    new (): HTMLPomHeaderIconItemElement;
  };

  interface HTMLPomHeaderItemElement extends Components.PomHeaderItem, HTMLStencilElement {}
  var HTMLPomHeaderItemElement: {
    prototype: HTMLPomHeaderItemElement;
    new (): HTMLPomHeaderItemElement;
  };

  interface HTMLPomHeaderElement extends Components.PomHeader, HTMLStencilElement {}
  var HTMLPomHeaderElement: {
    prototype: HTMLPomHeaderElement;
    new (): HTMLPomHeaderElement;
  };

  interface HTMLPomShareButtonElement extends Components.PomShareButton, HTMLStencilElement {}
  var HTMLPomShareButtonElement: {
    prototype: HTMLPomShareButtonElement;
    new (): HTMLPomShareButtonElement;
  };

  interface HTMLPomShareButtonsElement extends Components.PomShareButtons, HTMLStencilElement {}
  var HTMLPomShareButtonsElement: {
    prototype: HTMLPomShareButtonsElement;
    new (): HTMLPomShareButtonsElement;
  };

  interface HTMLPomTagsListItemElement extends Components.PomTagsListItem, HTMLStencilElement {}
  var HTMLPomTagsListItemElement: {
    prototype: HTMLPomTagsListItemElement;
    new (): HTMLPomTagsListItemElement;
  };

  interface HTMLPomTagsListElement extends Components.PomTagsList, HTMLStencilElement {}
  var HTMLPomTagsListElement: {
    prototype: HTMLPomTagsListElement;
    new (): HTMLPomTagsListElement;
  };

  interface HTMLPomTutorialCodeSnippetElement extends Components.PomTutorialCodeSnippet, HTMLStencilElement {}
  var HTMLPomTutorialCodeSnippetElement: {
    prototype: HTMLPomTutorialCodeSnippetElement;
    new (): HTMLPomTutorialCodeSnippetElement;
  };

  interface HTMLPomTutorialImageElement extends Components.PomTutorialImage, HTMLStencilElement {}
  var HTMLPomTutorialImageElement: {
    prototype: HTMLPomTutorialImageElement;
    new (): HTMLPomTutorialImageElement;
  };

  interface HTMLPomTutorialElement extends Components.PomTutorial, HTMLStencilElement {}
  var HTMLPomTutorialElement: {
    prototype: HTMLPomTutorialElement;
    new (): HTMLPomTutorialElement;
  };

  interface HTMLPomTutorialsListItemElement extends Components.PomTutorialsListItem, HTMLStencilElement {}
  var HTMLPomTutorialsListItemElement: {
    prototype: HTMLPomTutorialsListItemElement;
    new (): HTMLPomTutorialsListItemElement;
  };

  interface HTMLPomTutorialsListElement extends Components.PomTutorialsList, HTMLStencilElement {}
  var HTMLPomTutorialsListElement: {
    prototype: HTMLPomTutorialsListElement;
    new (): HTMLPomTutorialsListElement;
  };

  interface HTMLElementTagNameMap {
    'pom-header-icon-item': HTMLPomHeaderIconItemElement
    'pom-header-item': HTMLPomHeaderItemElement
    'pom-header': HTMLPomHeaderElement
    'pom-share-button': HTMLPomShareButtonElement
    'pom-share-buttons': HTMLPomShareButtonsElement
    'pom-tags-list-item': HTMLPomTagsListItemElement
    'pom-tags-list': HTMLPomTagsListElement
    'pom-tutorial-code-snippet': HTMLPomTutorialCodeSnippetElement
    'pom-tutorial-image': HTMLPomTutorialImageElement
    'pom-tutorial': HTMLPomTutorialElement
    'pom-tutorials-list-item': HTMLPomTutorialsListItemElement
    'pom-tutorials-list': HTMLPomTutorialsListElement
  }

  interface ElementTagNameMap {
    'pom-header-icon-item': HTMLPomHeaderIconItemElement;
    'pom-header-item': HTMLPomHeaderItemElement;
    'pom-header': HTMLPomHeaderElement;
    'pom-share-button': HTMLPomShareButtonElement;
    'pom-share-buttons': HTMLPomShareButtonsElement;
    'pom-tags-list-item': HTMLPomTagsListItemElement;
    'pom-tags-list': HTMLPomTagsListElement;
    'pom-tutorial-code-snippet': HTMLPomTutorialCodeSnippetElement;
    'pom-tutorial-image': HTMLPomTutorialImageElement;
    'pom-tutorial': HTMLPomTutorialElement;
    'pom-tutorials-list-item': HTMLPomTutorialsListItemElement;
    'pom-tutorials-list': HTMLPomTutorialsListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
