/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PomButtonCopyCode {
    'code': string;
  }
  interface PomButtonCopyCodeAttributes extends StencilHTMLAttributes {
    'code'?: string;
  }

  interface PomButtonCopyLink {
    'slug': string;
  }
  interface PomButtonCopyLinkAttributes extends StencilHTMLAttributes {
    'slug'?: string;
  }

  interface PomHeaderIconItem {
    'icon': string;
    'url': string;
  }
  interface PomHeaderIconItemAttributes extends StencilHTMLAttributes {
    'icon'?: string;
    'url'?: string;
  }

  interface PomHeaderItem {
    'description': string;
    'url': string;
  }
  interface PomHeaderItemAttributes extends StencilHTMLAttributes {
    'description'?: string;
    'url'?: string;
  }

  interface PomHeader {
    'mainTitle': string;
    'showPercentage': boolean;
    'subTitle': string;
  }
  interface PomHeaderAttributes extends StencilHTMLAttributes {
    'mainTitle'?: string;
    'showPercentage'?: boolean;
    'subTitle'?: string;
  }

  interface PomTagsListItem {
    'slug': string;
    'title': string;
  }
  interface PomTagsListItemAttributes extends StencilHTMLAttributes {
    'slug'?: string;
    'title'?: string;
  }

  interface PomTagsList {
    'slug': string;
    'title': string;
  }
  interface PomTagsListAttributes extends StencilHTMLAttributes {
    'slug'?: string;
    'title'?: string;
  }

  interface PomTutorialSectionCode {
    'code': string;
    'filename': string;
    'language': string;
  }
  interface PomTutorialSectionCodeAttributes extends StencilHTMLAttributes {
    'code'?: string;
    'filename'?: string;
    'language'?: string;
  }

  interface PomTutorialSectionCopy {
    'copy': string;
  }
  interface PomTutorialSectionCopyAttributes extends StencilHTMLAttributes {
    'copy'?: string;
  }

  interface PomTutorialSectionImage {
    'caption': string;
    'url': string;
  }
  interface PomTutorialSectionImageAttributes extends StencilHTMLAttributes {
    'caption'?: string;
    'url'?: string;
  }

  interface PomTutorialSection {
    'mainTitle': string;
    'slug': string;
  }
  interface PomTutorialSectionAttributes extends StencilHTMLAttributes {
    'mainTitle'?: string;
    'slug'?: string;
  }

  interface PomTutorial {
    'createdAt': string;
    'description': string;
    'duration': number;
    'mainTitle': string;
  }
  interface PomTutorialAttributes extends StencilHTMLAttributes {
    'createdAt'?: string;
    'description'?: string;
    'duration'?: number;
    'mainTitle'?: string;
  }

  interface PomTutorialsListItem {
    'createdAt': Date;
    'mainTitle': string;
    'shortDescription': string;
  }
  interface PomTutorialsListItemAttributes extends StencilHTMLAttributes {
    'createdAt'?: Date;
    'mainTitle'?: string;
    'shortDescription'?: string;
  }

  interface PomTutorialsList {}
  interface PomTutorialsListAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'PomButtonCopyCode': Components.PomButtonCopyCode;
    'PomButtonCopyLink': Components.PomButtonCopyLink;
    'PomHeaderIconItem': Components.PomHeaderIconItem;
    'PomHeaderItem': Components.PomHeaderItem;
    'PomHeader': Components.PomHeader;
    'PomTagsListItem': Components.PomTagsListItem;
    'PomTagsList': Components.PomTagsList;
    'PomTutorialSectionCode': Components.PomTutorialSectionCode;
    'PomTutorialSectionCopy': Components.PomTutorialSectionCopy;
    'PomTutorialSectionImage': Components.PomTutorialSectionImage;
    'PomTutorialSection': Components.PomTutorialSection;
    'PomTutorial': Components.PomTutorial;
    'PomTutorialsListItem': Components.PomTutorialsListItem;
    'PomTutorialsList': Components.PomTutorialsList;
  }

  interface StencilIntrinsicElements {
    'pom-button-copy-code': Components.PomButtonCopyCodeAttributes;
    'pom-button-copy-link': Components.PomButtonCopyLinkAttributes;
    'pom-header-icon-item': Components.PomHeaderIconItemAttributes;
    'pom-header-item': Components.PomHeaderItemAttributes;
    'pom-header': Components.PomHeaderAttributes;
    'pom-tags-list-item': Components.PomTagsListItemAttributes;
    'pom-tags-list': Components.PomTagsListAttributes;
    'pom-tutorial-section-code': Components.PomTutorialSectionCodeAttributes;
    'pom-tutorial-section-copy': Components.PomTutorialSectionCopyAttributes;
    'pom-tutorial-section-image': Components.PomTutorialSectionImageAttributes;
    'pom-tutorial-section': Components.PomTutorialSectionAttributes;
    'pom-tutorial': Components.PomTutorialAttributes;
    'pom-tutorials-list-item': Components.PomTutorialsListItemAttributes;
    'pom-tutorials-list': Components.PomTutorialsListAttributes;
  }


  interface HTMLPomButtonCopyCodeElement extends Components.PomButtonCopyCode, HTMLStencilElement {}
  var HTMLPomButtonCopyCodeElement: {
    prototype: HTMLPomButtonCopyCodeElement;
    new (): HTMLPomButtonCopyCodeElement;
  };

  interface HTMLPomButtonCopyLinkElement extends Components.PomButtonCopyLink, HTMLStencilElement {}
  var HTMLPomButtonCopyLinkElement: {
    prototype: HTMLPomButtonCopyLinkElement;
    new (): HTMLPomButtonCopyLinkElement;
  };

  interface HTMLPomHeaderIconItemElement extends Components.PomHeaderIconItem, HTMLStencilElement {}
  var HTMLPomHeaderIconItemElement: {
    prototype: HTMLPomHeaderIconItemElement;
    new (): HTMLPomHeaderIconItemElement;
  };

  interface HTMLPomHeaderItemElement extends Components.PomHeaderItem, HTMLStencilElement {}
  var HTMLPomHeaderItemElement: {
    prototype: HTMLPomHeaderItemElement;
    new (): HTMLPomHeaderItemElement;
  };

  interface HTMLPomHeaderElement extends Components.PomHeader, HTMLStencilElement {}
  var HTMLPomHeaderElement: {
    prototype: HTMLPomHeaderElement;
    new (): HTMLPomHeaderElement;
  };

  interface HTMLPomTagsListItemElement extends Components.PomTagsListItem, HTMLStencilElement {}
  var HTMLPomTagsListItemElement: {
    prototype: HTMLPomTagsListItemElement;
    new (): HTMLPomTagsListItemElement;
  };

  interface HTMLPomTagsListElement extends Components.PomTagsList, HTMLStencilElement {}
  var HTMLPomTagsListElement: {
    prototype: HTMLPomTagsListElement;
    new (): HTMLPomTagsListElement;
  };

  interface HTMLPomTutorialSectionCodeElement extends Components.PomTutorialSectionCode, HTMLStencilElement {}
  var HTMLPomTutorialSectionCodeElement: {
    prototype: HTMLPomTutorialSectionCodeElement;
    new (): HTMLPomTutorialSectionCodeElement;
  };

  interface HTMLPomTutorialSectionCopyElement extends Components.PomTutorialSectionCopy, HTMLStencilElement {}
  var HTMLPomTutorialSectionCopyElement: {
    prototype: HTMLPomTutorialSectionCopyElement;
    new (): HTMLPomTutorialSectionCopyElement;
  };

  interface HTMLPomTutorialSectionImageElement extends Components.PomTutorialSectionImage, HTMLStencilElement {}
  var HTMLPomTutorialSectionImageElement: {
    prototype: HTMLPomTutorialSectionImageElement;
    new (): HTMLPomTutorialSectionImageElement;
  };

  interface HTMLPomTutorialSectionElement extends Components.PomTutorialSection, HTMLStencilElement {}
  var HTMLPomTutorialSectionElement: {
    prototype: HTMLPomTutorialSectionElement;
    new (): HTMLPomTutorialSectionElement;
  };

  interface HTMLPomTutorialElement extends Components.PomTutorial, HTMLStencilElement {}
  var HTMLPomTutorialElement: {
    prototype: HTMLPomTutorialElement;
    new (): HTMLPomTutorialElement;
  };

  interface HTMLPomTutorialsListItemElement extends Components.PomTutorialsListItem, HTMLStencilElement {}
  var HTMLPomTutorialsListItemElement: {
    prototype: HTMLPomTutorialsListItemElement;
    new (): HTMLPomTutorialsListItemElement;
  };

  interface HTMLPomTutorialsListElement extends Components.PomTutorialsList, HTMLStencilElement {}
  var HTMLPomTutorialsListElement: {
    prototype: HTMLPomTutorialsListElement;
    new (): HTMLPomTutorialsListElement;
  };

  interface HTMLElementTagNameMap {
    'pom-button-copy-code': HTMLPomButtonCopyCodeElement
    'pom-button-copy-link': HTMLPomButtonCopyLinkElement
    'pom-header-icon-item': HTMLPomHeaderIconItemElement
    'pom-header-item': HTMLPomHeaderItemElement
    'pom-header': HTMLPomHeaderElement
    'pom-tags-list-item': HTMLPomTagsListItemElement
    'pom-tags-list': HTMLPomTagsListElement
    'pom-tutorial-section-code': HTMLPomTutorialSectionCodeElement
    'pom-tutorial-section-copy': HTMLPomTutorialSectionCopyElement
    'pom-tutorial-section-image': HTMLPomTutorialSectionImageElement
    'pom-tutorial-section': HTMLPomTutorialSectionElement
    'pom-tutorial': HTMLPomTutorialElement
    'pom-tutorials-list-item': HTMLPomTutorialsListItemElement
    'pom-tutorials-list': HTMLPomTutorialsListElement
  }

  interface ElementTagNameMap {
    'pom-button-copy-code': HTMLPomButtonCopyCodeElement;
    'pom-button-copy-link': HTMLPomButtonCopyLinkElement;
    'pom-header-icon-item': HTMLPomHeaderIconItemElement;
    'pom-header-item': HTMLPomHeaderItemElement;
    'pom-header': HTMLPomHeaderElement;
    'pom-tags-list-item': HTMLPomTagsListItemElement;
    'pom-tags-list': HTMLPomTagsListElement;
    'pom-tutorial-section-code': HTMLPomTutorialSectionCodeElement;
    'pom-tutorial-section-copy': HTMLPomTutorialSectionCopyElement;
    'pom-tutorial-section-image': HTMLPomTutorialSectionImageElement;
    'pom-tutorial-section': HTMLPomTutorialSectionElement;
    'pom-tutorial': HTMLPomTutorialElement;
    'pom-tutorials-list-item': HTMLPomTutorialsListItemElement;
    'pom-tutorials-list': HTMLPomTutorialsListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
