/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppTutorial {
    'match': MatchResults;
  }
  interface AppTutorialAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface PomHeaderIconItem {
    'icon': string;
    'url': string;
  }
  interface PomHeaderIconItemAttributes extends StencilHTMLAttributes {
    'icon'?: string;
    'url'?: string;
  }

  interface PomHeaderTextItem {
    'description': string;
    'url': string;
  }
  interface PomHeaderTextItemAttributes extends StencilHTMLAttributes {
    'description'?: string;
    'url'?: string;
  }

  interface PomHeader {
    'mainTitle': string;
    'showPercentage': boolean;
    'subTitle': string;
  }
  interface PomHeaderAttributes extends StencilHTMLAttributes {
    'mainTitle'?: string;
    'showPercentage'?: boolean;
    'subTitle'?: string;
  }

  interface PomShareButtons {
    'tutorialTitle': string;
  }
  interface PomShareButtonsAttributes extends StencilHTMLAttributes {
    'tutorialTitle'?: string;
  }

  interface PomTagsList {
    'tags': string[];
  }
  interface PomTagsListAttributes extends StencilHTMLAttributes {
    'tags'?: string[];
  }

  interface PomTutorialCodeSnippet {
    'code': string;
    'language': string;
  }
  interface PomTutorialCodeSnippetAttributes extends StencilHTMLAttributes {
    'code'?: string;
    'language'?: string;
  }

  interface PomTutorialImage {
    'alt': string;
    'caption': string;
    'src': string;
  }
  interface PomTutorialImageAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'caption'?: string;
    'src'?: string;
  }

  interface PomTutorial {
    'content': string;
    'createdAt': Date;
    'duration': number;
    'tags': string;
    'tutorialTitle': string;
  }
  interface PomTutorialAttributes extends StencilHTMLAttributes {
    'content'?: string;
    'createdAt'?: Date;
    'duration'?: number;
    'tags'?: string;
    'tutorialTitle'?: string;
  }

  interface PomTutorialsListItem {
    'createdAt': Date;
    'description': string;
    'tags': string;
    'tutorialTitle': string;
  }
  interface PomTutorialsListItemAttributes extends StencilHTMLAttributes {
    'createdAt'?: Date;
    'description'?: string;
    'tags'?: string;
    'tutorialTitle'?: string;
  }

  interface PomTutorialsList {}
  interface PomTutorialsListAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'AppTutorial': Components.AppTutorial;
    'PomHeaderIconItem': Components.PomHeaderIconItem;
    'PomHeaderTextItem': Components.PomHeaderTextItem;
    'PomHeader': Components.PomHeader;
    'PomShareButtons': Components.PomShareButtons;
    'PomTagsList': Components.PomTagsList;
    'PomTutorialCodeSnippet': Components.PomTutorialCodeSnippet;
    'PomTutorialImage': Components.PomTutorialImage;
    'PomTutorial': Components.PomTutorial;
    'PomTutorialsListItem': Components.PomTutorialsListItem;
    'PomTutorialsList': Components.PomTutorialsList;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'app-tutorial': Components.AppTutorialAttributes;
    'pom-header-icon-item': Components.PomHeaderIconItemAttributes;
    'pom-header-text-item': Components.PomHeaderTextItemAttributes;
    'pom-header': Components.PomHeaderAttributes;
    'pom-share-buttons': Components.PomShareButtonsAttributes;
    'pom-tags-list': Components.PomTagsListAttributes;
    'pom-tutorial-code-snippet': Components.PomTutorialCodeSnippetAttributes;
    'pom-tutorial-image': Components.PomTutorialImageAttributes;
    'pom-tutorial': Components.PomTutorialAttributes;
    'pom-tutorials-list-item': Components.PomTutorialsListItemAttributes;
    'pom-tutorials-list': Components.PomTutorialsListAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppTutorialElement extends Components.AppTutorial, HTMLStencilElement {}
  var HTMLAppTutorialElement: {
    prototype: HTMLAppTutorialElement;
    new (): HTMLAppTutorialElement;
  };

  interface HTMLPomHeaderIconItemElement extends Components.PomHeaderIconItem, HTMLStencilElement {}
  var HTMLPomHeaderIconItemElement: {
    prototype: HTMLPomHeaderIconItemElement;
    new (): HTMLPomHeaderIconItemElement;
  };

  interface HTMLPomHeaderTextItemElement extends Components.PomHeaderTextItem, HTMLStencilElement {}
  var HTMLPomHeaderTextItemElement: {
    prototype: HTMLPomHeaderTextItemElement;
    new (): HTMLPomHeaderTextItemElement;
  };

  interface HTMLPomHeaderElement extends Components.PomHeader, HTMLStencilElement {}
  var HTMLPomHeaderElement: {
    prototype: HTMLPomHeaderElement;
    new (): HTMLPomHeaderElement;
  };

  interface HTMLPomShareButtonsElement extends Components.PomShareButtons, HTMLStencilElement {}
  var HTMLPomShareButtonsElement: {
    prototype: HTMLPomShareButtonsElement;
    new (): HTMLPomShareButtonsElement;
  };

  interface HTMLPomTagsListElement extends Components.PomTagsList, HTMLStencilElement {}
  var HTMLPomTagsListElement: {
    prototype: HTMLPomTagsListElement;
    new (): HTMLPomTagsListElement;
  };

  interface HTMLPomTutorialCodeSnippetElement extends Components.PomTutorialCodeSnippet, HTMLStencilElement {}
  var HTMLPomTutorialCodeSnippetElement: {
    prototype: HTMLPomTutorialCodeSnippetElement;
    new (): HTMLPomTutorialCodeSnippetElement;
  };

  interface HTMLPomTutorialImageElement extends Components.PomTutorialImage, HTMLStencilElement {}
  var HTMLPomTutorialImageElement: {
    prototype: HTMLPomTutorialImageElement;
    new (): HTMLPomTutorialImageElement;
  };

  interface HTMLPomTutorialElement extends Components.PomTutorial, HTMLStencilElement {}
  var HTMLPomTutorialElement: {
    prototype: HTMLPomTutorialElement;
    new (): HTMLPomTutorialElement;
  };

  interface HTMLPomTutorialsListItemElement extends Components.PomTutorialsListItem, HTMLStencilElement {}
  var HTMLPomTutorialsListItemElement: {
    prototype: HTMLPomTutorialsListItemElement;
    new (): HTMLPomTutorialsListItemElement;
  };

  interface HTMLPomTutorialsListElement extends Components.PomTutorialsList, HTMLStencilElement {}
  var HTMLPomTutorialsListElement: {
    prototype: HTMLPomTutorialsListElement;
    new (): HTMLPomTutorialsListElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'app-tutorial': HTMLAppTutorialElement
    'pom-header-icon-item': HTMLPomHeaderIconItemElement
    'pom-header-text-item': HTMLPomHeaderTextItemElement
    'pom-header': HTMLPomHeaderElement
    'pom-share-buttons': HTMLPomShareButtonsElement
    'pom-tags-list': HTMLPomTagsListElement
    'pom-tutorial-code-snippet': HTMLPomTutorialCodeSnippetElement
    'pom-tutorial-image': HTMLPomTutorialImageElement
    'pom-tutorial': HTMLPomTutorialElement
    'pom-tutorials-list-item': HTMLPomTutorialsListItemElement
    'pom-tutorials-list': HTMLPomTutorialsListElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'app-tutorial': HTMLAppTutorialElement;
    'pom-header-icon-item': HTMLPomHeaderIconItemElement;
    'pom-header-text-item': HTMLPomHeaderTextItemElement;
    'pom-header': HTMLPomHeaderElement;
    'pom-share-buttons': HTMLPomShareButtonsElement;
    'pom-tags-list': HTMLPomTagsListElement;
    'pom-tutorial-code-snippet': HTMLPomTutorialCodeSnippetElement;
    'pom-tutorial-image': HTMLPomTutorialImageElement;
    'pom-tutorial': HTMLPomTutorialElement;
    'pom-tutorials-list-item': HTMLPomTutorialsListItemElement;
    'pom-tutorials-list': HTMLPomTutorialsListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
